"""
Emotional reaction generator for interview questions
"""
import random
from typing import Optional

from ..generation.constants import (
    REACTION_PROBABILITY,
    QUALITY_THRESHOLD_EXCELLENT,
    QUALITY_THRESHOLD_GOOD,
    QUALITY_THRESHOLD_SURPRISE,
    MID_CONVERSATION_QA,
    GREETINGS,
    ENCOURAGEMENTS,
    CONGRATULATIONS,
    SURPRISE_REACTIONS,
    TRANSITIONS
)


def generate_emotional_reaction(
    previous_answer: Optional[str],
    quality_score: float,
    qa_count: int,
    is_first_question: bool = False
) -> str:
    """
    Generate emotional reaction based on answer quality and context
    NOTE: First question greeting is now generated by the model itself
    
    Args:
        previous_answer: Previous answer text
        quality_score: Quality score from answer analyzer (0.0-1.0)
        qa_count: Number of Q&A pairs so far
        is_first_question: True if this is the first question (greeting in model output)
    
    Returns:
        Emotional reaction string (or empty string)
    """
    # First question - model will generate greeting, no template needed
    if is_first_question:
        return ""
    
    # No reaction for no previous answer or randomly skip
    if not previous_answer or random.random() > REACTION_PROBABILITY:
        return ""
    
    # Second question - acknowledge first answer
    if qa_count == 1:
        return random.choice(GREETINGS)
    
    # Excellent answer - congratulate
    if quality_score >= QUALITY_THRESHOLD_SURPRISE:
        return random.choice(SURPRISE_REACTIONS)
    
    if quality_score >= QUALITY_THRESHOLD_EXCELLENT:
        return random.choice(CONGRATULATIONS)
    
    # Good answer - encourage
    if quality_score >= QUALITY_THRESHOLD_GOOD:
        return random.choice(ENCOURAGEMENTS)
    
    # Mid-conversation transition
    if qa_count >= MID_CONVERSATION_QA:
        return random.choice(TRANSITIONS)
    
    return ""
